apiVersion: apps/v1
kind: Deployment
metadata:
  name: corerpc
  namespace: simple_admin
  labels:
    app: corerpc
spec:
  replicas: 3
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: corerpc
  template:
    metadata:
      labels:
        app: corerpc
    spec:
      containers:
      - name: corerpc
        image: corerpc:0.0.1
        ports:
        - containerPort: 9101
        readinessProbe:
          tcpSocket:
            port: 9101
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 9101
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1024Mi
        volumeMounts:
        - name: timezone
          mountPath: /etc/localtime
      volumes:
        - name: timezone
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai

---

apiVersion: v1
kind: Service
metadata:
  name: corerpc-svc
  namespace: simple_admin
spec:
  ports:
  - port: 9101
    targetPort: 9101
  selector:
    app: corerpc

---

apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: corerpc-hpa-c
  namespace: simple_admin
  labels:
    app: corerpc-hpa-c
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: corerpc
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 80

---

apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: corerpc-hpa-m
  namespace: simple_admin
  labels:
    app: corerpc-hpa-m
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: corerpc
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 80
