apiVersion: apps/v1
kind: Deployment
metadata:
  name: corerpc
  namespace: simple-admin
  labels:
    app: corerpc
spec:
  replicas: 3
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: corerpc
  template:
    metadata:
      labels:
        app: corerpc
    spec:
      serviceAccountName: endpoints-finder
      containers:
      - name: corerpc
        image: ryanpower/corerpc:0.0.20
        ports:
        - containerPort: 9101
        readinessProbe:
          tcpSocket:
            port: 9101
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 9101
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 1000m
            memory: 1024Mi
        volumeMounts:
        - name: timezone
          mountPath: /etc/localtime
      volumes:
        - name: timezone
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai

---

apiVersion: v1
kind: Service
metadata:
  name: corerpc-svc
  namespace: simple-admin
spec:
  ports:
  - port: 9101
    targetPort: 9101
  - port: 4001
    name: prometheus
    targetPort: 4001
  selector:
    app: corerpc

---

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: corerpc
  labels:
    team: core
spec:
  selector:
    matchLabels:
      app: corerpc
  endpoints:
    - port: prometheus

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: corerpc-hpa-c
  namespace: simple-admin
  labels:
    app: corerpc-hpa-c
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: corerpc
  minReplicas: 3
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: corerpc-hpa-m
  namespace: simple-admin
  labels:
    app: corerpc-hpa-m
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: corerpc
  minReplicas: 3
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
