apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    prometheus: k8s
  name: k8s
  namespace: monitoring
spec:
  serviceMonitorNamespaceSelector:
    matchLabels:
      name: simple-admin