apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-simple-admin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-simple-admin
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - nodes/metrics
      - services
      - endpoints
      - pods
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources:
      - configmaps
    verbs: ["get"]
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs: ["get", "list", "watch"]
  - nonResourceURLs: ["/metrics"]
    verbs: ["get"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-simple-admin
  namespace: simple-admin
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - endpoints
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-simple-admin
  namespace: simple-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-simple-admin
subjects:
  - kind: ServiceAccount
    name: prometheus-simple-admin
    namespace: monitoring